wallsite/partymaster/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

from .views import (index,
                    Logme,
                    Login,
                    Signup,
                    log_me_out,
                    Activity,
                    activate,
                    ActivityDetail,
                    )

app_name = "partymaster"

urlpatterns = [
    url(r'^$', index, name="index"),
    url(r'^logme$', Logme.as_view(), name="logme"),
    url(r'^activity$', Activity.as_view(), name="Activity"),
    url(r'^activity/detail/(?P<id>[0-9]+)[/]*$', ActivityDetail.as_view(), name="show_detail"),
    url(r'^activity/detail/', ActivityDetail.as_view(), name="show_detail"),
    url(r'^activity/(?P<user>\w+)', Activity.as_view(), name='show_my_activity'),
    url(r'^activity/(?P<user>\w+)', Activity.as_view(), name='activity_created_by_me'),
    url(r'^activity', Activity.as_view(), name="activityCRUD"),
    url(r'^login$', Login.as_view(), name="login"),
    url(r'^signup$', Signup.as_view(), name="signup"),
    url(r'^activate/(?P<accode>\w+)$', activate, name='activate'),
    url(r'^logout$', log_me_out, name="logout"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wallsite/wallsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('partymaster.urls')),
]

wallsite/partymaster/models.py
# coding:utf-8
from __future__ import unicode_literals
import time
from datetime import timedelta
from django.db import models
from django.contrib.auth.models import User


"""
用户行为：
用户：
1. 发布活动
2. 浏览活动
3. 注册参与活动
4. 注册账户
5. 修改账户信息

管理员：
管理用户和活动

活动信息：
开放程度：怎样看到活动信息
   发布者可以选择活动的开放程度，level 3 为所有人可见， level 2 为可以通过链接访问，level 3 的活动信息需要正确回答过验证信息才能访问。
参与人：一组数据记录参与者的信息
   【e-mail、名称元组列表】用来记录参与者信息，因为参与活动并不需要特别注册账户。
"""

default_live_time = timedelta(days=7)
OPEN_CHOICES = (
        (1, '输入验证码可见'),
        (2, '仅凭链接访问，不会在首页公开'),
        (3, '在网站首页公开'),
)

ACT_CHOICES = (
        ('academic', '学术'),
        ('social', '社交'),
        ('recruit', '招聘'),
)


class activity(models.Model):
    id = models.CharField(primary_key=True, editable=False, max_length=20)
    title = models.CharField(max_length=200, null=False, verbose_name='活动标题')
    detail = models.TextField(null=True, verbose_name='详细描述')
    host = models.CharField(max_length=400, null=False, verbose_name='举办方')
    poster = models.ForeignKey(User)
    attendees = models.TextField(null=True)
    open_level = models.IntegerField(null=False, default=3, choices=OPEN_CHOICES, verbose_name='信息开放等级')
    post_time = models.DateTimeField(auto_now_add=True)
    start_time = models.DateTimeField(null=False, verbose_name='开始时间')
    freeze_time = models.DateTimeField(null=False, verbose_name='注册冻结时间')
    tags = models.CharField(max_length=100, choices=ACT_CHOICES, verbose_name='标签')
    pass_word = models.CharField(max_length=20, verbose_name='活动密令', null=True)
    img = models.ImageField(upload_to='img', verbose_name='微信群二维码', null=True)
    def get_url(self):
        return "/activity/detail/{id}".format(id = self.id)

wallsite/partymaster/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import activity

from datetimewidget.widgets import DateTimeWidget


class LoginForm(forms.Form):
    username = forms.CharField(label='username', max_length=15)
    password = forms.CharField(widget=forms.PasswordInput)


class SignupForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password']

class ActivityForm(forms.ModelForm):
    start_time = forms.DateTimeField(label='活动开始时间', widget=DateTimeWidget(usel10n=True, bootstrap_version=3))
    freeze_time = forms.DateTimeField(label='注册截止时间', widget=DateTimeWidget(usel10n=True, bootstrap_version=3))
    pass_word = forms.CharField(label='活动密令', max_length=20, initial="*")
    class Meta:
        model = activity
        fields = ["title","detail","host", "open_level", 
        "start_time", "freeze_time", "tags", "pass_word", "img"]


class SubscribeUser(forms.Form):
    name = forms.CharField(label='姓名', max_length=20, error_messages={'required': 'Please enter your name'})
    email = forms.EmailField(help_text='A valid email address, please.')

class VerifyForm(forms.Form):
    pass_word = forms.CharField(label='详情开启口令', max_length=100, error_messages={'required': '输入密令才能查看活动详情'})

wallsite/partymaster/views.py
# coding:utf-8
from datetime import datetime, timedelta
import time
import logging
import os
from PIL import Image

from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.views.generic import View
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.conf import settings
from .forms import(LoginForm,
                   SignupForm,
                   ActivityForm,
                   SubscribeUser,
                   VerifyForm,
                   )
from .models import activity

# from .maintainer import main
# main.every_1_day_task()

# Get an instance of a logger
logger = logging.getLogger(__name__)


# 生成 activity 的算法
def get_Aid():
    a, b = str(time.time()).split('.')
    return str(int(a)*int(b))


def get_activate_id(id, username: str):
    return str(id) + str(hex(int("".join(map(lambda x:str(ord(x)), username)))))


def index(request):
    return Activity.as_view()(request)


class Activity(View):
    def get(self, request, *args, **kwargs):
        user_name = kwargs.get('user', '')
        period_str = kwargs.get('period', '')
        tag = request.GET.get('tag', '')
        period = timedelta(
            days=(min(3, int(period_str)) if period_str.isdigit() else 3))	# 限制显示的活动时间范围
        # route /activity/
        if not user_name:
            activities = activity.objects.filter(start_time__gte=datetime.now()-period).filter(open_level__gte=3).order_by(
                '-post_time')  # .exclude(title__isnull=True).exclude(title__exact='').order_by('-comments_number')[:20]
            if tag:
                activities = activities.filter(tags=tag)
            for a_i in activities:
                a_i.people_count = a_i.attendees.count(";")
            return render(request, 'activity/activities.html',
                          {
                              "activities": activities,
                          }
                )
        # route /activity/my
        elif request.user.is_authenticated() and user_name=="my":
            type = request.GET.get('t', '1')
            # Joined activities about current user
            if type == '1':
                activities = activity.objects.filter(
                    attendees__contains=request.user.email)
            # Activities created by current user
            elif type == '2':
                start_str = request.user.first_name + \
                            request.user.last_name + "," \
                            + request.user.email + ";"
                activities = activity.objects.filter(attendees__contains=start_str)
            if type in ["1", "2"]:
                if tag:
                    activities = activities.filter(tags=tag)
                for a_i in activities:
                    a_i.people_count = a_i.attendees.count(";")
                return render(request, 'activity/activities.html',
                              {
                                  "activities": activities,
                              }
                              )
            elif type == "3":
                form = ActivityForm()
                context = {
                    'form': form,
                    'feedback': "",
                }
                # Page to create activity
                return render(request, 'activity/createActivity.html', context)
        else:
            return redirect('partymaster:Activity')

    def post(self, request, *args, **kwargs):
        # 获取来自Form的表单数据
        form = ActivityForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            # 创建实例，需要做些数据处理，暂不做保存
            instance = form.save(commit=False)
            instance.id = get_Aid()
            # 将登录用户作为登记人
            instance.poster = request.user
            instance.attendees = request.user.first_name + request.user.last_name + "," \
                                 + request.user.email + ";"
            # 保存该实例
            instance.save()
            # 对非公开链接发送邮件给活动发布人
            if instance.open_level < 3:
                try:
                    user = instance.poster
                    activity_link = "http://" + settings.HOST_ADDRESS + "/activity/detail/" + str(instance.id)
                    send_mail('您发起了活动 {TITLE}'.format(TITLE=instance.title),
                              "{FirstName} {LastName},\n您的活动链接是 {LINK}".format(
                                  FirstName=user.first_name,
                                  LastName=user.last_name,
                                  LINK=activity_link),
                              settings.EMAIL_HOST_USER,
                              [user.email],
                              fail_silently=False, )
                except Exception as e:
                    return HttpResponse('Problem sending activity information link:' +
                                        str(e))
            # 跳转至列表页面
            return redirect('partymaster:Activity')
            # 创建context来集中处理需要传递到页面的数据
        context = {
            'form': form,
            'feedback': "",
        }
        # 如果没有有效提交，则仍留在原来页面
        return render(request, 'activity/createActivity.html', context)


class ActivityDetail(View):
    form_class = SubscribeUser

    def post(self, request, *args, **kwargs):
        """ 安全漏洞：如果用户直接向此链接用 post 方式提交email和user数据就可以订阅活动，
            而不需要输入验证码，此处采用更复杂的活动id来减小风险
        """
        tag = request.GET.get('t', '')
        act = get_object_or_404(activity, id=kwargs["id"])
        # 更新二维码图片
        if "image" in request.FILES and request.user.is_authenticated() and \
                act.attendees.startswith(
                    request.user.first_name +
                    request.user.last_name + "," 
                    + request.user.email + ";"):
            image = request.FILES["image"]
            img= Image.open(image)
            img.thumbnail((200,200), Image.ANTIALIAS)
            img_path = (settings.BASE_DIR + act.img.url).replace("\\", "/")
            img.save(img_path,"jpeg")
            return render(request, 'activity/sub_success.html',
                          {'msg': '<h3>头像修改成功</h3>'})
        if "image" not in request.FILES and tag == "1":
            return redirect(request.path)
        if act.open_level <= 1:
            form = VerifyForm(request.POST or None)
            if form.is_valid():
                pass_word = form.cleaned_data['pass_word']
                if pass_word != act.pass_word:
                    context_data = {"form": form, 'feedback': "口令错误"}
                    return render(request, 'activity/verify.html', context_data)
                context_data = {"activity": act, "form": SubscribeUser()}
                return render(request, 'activity/detail.html', context_data)
            if "email" not in request.POST:
                context_data = {"form": VerifyForm(), 'feedback': ""}
                return render(request, 'activity/verify.html', context_data)
        if request.user.is_authenticated():
            name = (request.user.first_name + request.user.last_name)
            email = request.user.email
            if email in act.attendees:
                return render(request, 'activity/sub_success.html',
                              {'msg': '<h3>你的邮箱已被加入过了！</h3>'})
            append_str = "%s,%s;"%(name,email)
            act.attendees += append_str
            act.save()
            return render(request, 'activity/sub_success.html',
                          {'msg': '<h3>订阅成功</h3>'})
        form = self.form_class(request.POST or None)
        if form.is_valid():  # 如果提交的数据合法
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            if email in act.attendees:
                return render(request, 'activity/sub_success.html',
                              {'msg': '<h3>你的邮箱已被加入过了！</h3>'})
            append_str = "%s,%s;"%(name,email)
            act.attendees += append_str
            act.save()
            return render(request, 'activity/sub_success.html',
                          {'msg': '<h3>订阅成功</h3>'})
        context_data = {"activity": act, "form": form}
        return render(request, 'activity/detail.html', context_data)

    def get(self, request, *args, **kwargs):
        act = get_object_or_404(activity, id=kwargs["id"])
        if act.open_level <= 1:
            context_data = {"form": VerifyForm(), 'feedback': ""}
            return render(request, 'activity/verify.html', context_data)
        # 判断已经登陆的用户是不是这个活动的发起者
        if request.user.is_authenticated() and \
            act.attendees.startswith(
                request.user.first_name +
                request.user.last_name + "," 
                + request.user.email + ";"):
            context_data = {"activity":act, "IsOwner":True}
        else:
            Form = SubscribeUser()
            context_data = {"activity":act, "form":Form}
        context_data["random_str"] = str(time.time())
        if datetime.now() > act.start_time:
            context_data["out_of_date"] = True
        return render(request, 'activity/detail.html', context_data)


def check_login_status(request):
    if not request.user.is_authenticated():
        return redirect('partymaster:index')


class Logme(View):
    def get(self, request, *args, **kwargs):
        loginForm = LoginForm()
        signupForm = SignupForm()
        context_data = {
            'loginForm': loginForm,
            'signupForm': signupForm
        }
        return render(request, 'login.html', context_data)


class Login(View):
    form_class = LoginForm

    def post(self, request, *args, **kwargs):
        loginForm = self.form_class(request.POST or None)
        signupForm = SignupForm()
        context_data = {

wallsite/partymaster/templates/activate.html
{% extends 'base.html'%}

{% block content %}
    <div class="container text-center">
        {{ msg | safe }}
    </div>
{% endblock %}

wallsite/partymaster/templates/base.html
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <!-- 百度统计 <<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"/>end-->
    {% block navbar_css %}{% endblock navbar_css %}
</head>
<body>
{% block navbar %}{% endblock navbar %}
<div class="container">
{% if msg_suc %}
    <div class="alert alert-dismissible alert-success text-center">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{msg_suc| safe}}
      </div>
{% elif msg_info %}
    <div class="alert alert-dismissible alert-info text-center">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{msg_info| safe}}
      </div>
{% elif msg_err %}
    <div class="alert alert-dismissible alert-danger text-center">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{msg_err| safe}}
      </div>
{% endif %}
{% block content %}

{% endblock %}
</div>
    <!-- footer start -->
    <footer align="center" style="bottom: 0; margin-top: 20px;">
            <small>All Rights Reserved 2014-{% now "Y" %}</small>
    </footer>
    <!-- footer end -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha256-k2WSCIexGzOj3Euiig+TlR8gA0EmPjuc79OEeY5L45g="
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

wallsite/partymaster/templates/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-md-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

wallsite/partymaster/templates/login.html
{% extends 'base.html' %}

{% block title %}登录{% endblock %}

{% block content %}
    <div class="row">
        <h3 class="well">Login</h3>
        <form method="post" action="{% url 'partymaster:login'%}">
                {% csrf_token %}
                {% include 'form_template.html' with form=loginForm %}
                <div class="form-group">
                    <div class="col-md-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-success">Login</button>
                    </div>
                </div>
            </form>
    </div>
    <div class="row">
        <h3 class="well">SignUp</h3>
        <form method="post" action="{% url 'partymaster:signup'%}">
                {% csrf_token %}
                {% include 'form_template.html' with form=signupForm %}
                <div class="form-group">
                    <div class="col-md-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-success">Signup</button>
                    </div>
                </div>
            </form>
    </div>
{% endblock %}

wallsite/partymaster/templates/navbar.html
{% extends "base.html" %}
{% block navbar_css %}
{% block content_css %}
{% endblock %}
<style>
    html {
        height: 100%;
    }
    body {
        min-height: 100%;
        position: relative;
        padding-bottom: 74px;
        padding-top: 74px;
    }
    
    /*------for notes------*/

    
    /* -----for navbar----- */
    .navbar {
        background: #FFF8DC;
    }
    /* -----for footer----- */
    #site_footer {
        position: absolute;
        bottom: 0;
        left: 0;
        right: 0;
        overflow: hidden;
        height: 74px;
        color: #999;
    }
    #site_footer .container {
        padding-bottom: 10px;
    }
    #site_footer .container .footer_text {
        padding-top: 18px;
        color: black;
        font-size: 15px;
    }
    #site_footer p {
        margin-top: 10px;
        margin-bottom: 10px;
        font-size: 15px;
    }
    #site_navbar .container a {
        font-size: 15px;
        color: black;
        background: #FFEC8B;
    }
    #site_navbar .container li.active a {
        background: #FFC125;
    }
</style>
{% endblock navbar_css %}
{% block navbar %}
<div class="container">
    <div class="row clearfix">
        <div class="col-md-12 column">
            <div class="jumbotron">
                <h1><font face="微软雅黑" color="#8B008B"><a href="/activity" title="home">
                    ❤Party Master
                    </a>
                    </font>
                </h1>
                <p>
                    有事就贴出来吧
                </p>
                <div class="container">
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'partymaster:logout' %}" style="margin:1em 1em 1em 1em;" class="btn btn-danger pull-right">Logout</a>
                    {% else %}
                        <a href="{% url 'partymaster:logme' %}" style="margin:1em 1em 1em 1em;" class="btn btn-danger pull-right">LogIn/SignIn</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-md-12 column">
            <ul class="nav nav-pills">
                <li class="active">
                     <a href="/">首页</a>
                </li>
                {% if request.user.is_authenticated %}
                <li>
                     <a href="/activity/my?t=1">我的订阅</a>
                </li>
                <li>
                     <a href="/activity/my?t=2">我的发布</a>
                </li>
                <li>
                    <a href="/activity/my?t=3">发布新活动</a>
                </li>
                {% endif %}
            </ul>
            <div align="center"><p>按标签分类：</p>
             <span class="label label-success"><a href="/activity/?tag=academic">学术</a></span>
             <span class="label label-success"><a href="/activity/?tag=social">社交</a></span>
             <span class="label label-success"><a href="/activity/?tag=work">工作</a></span>
             <span class="label label-info"><a href="/activity">所有活动</a></span>
            </div>
        </div>
    </div>
</div>
{% endblock navbar %}

wallsite/partymaster/templates/profile.html
{% extends 'navbar.html' %}

{% block title %}个人信息{% endblock %}

{% block content %}
    <div class="row text-center">
    <div class="col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3">
        <h3 class="well">Profile</h3>
    </div>
    </div>
    <div class="row text-center">
            <div style="color:white;background-color: #547dc4;border-radius: 5px;" class="col-sm-4 col-md-2 col-md-offset-3 col-lg-2 col-lg-offset-3">
                    <h3>First Name</h3>
            </div>
            <div style="color:white;background-color: #547dc4;border-radius: 5px;" class="col-sm-8 col-md-4 col-lg-4">
                    <h3 class="pull-left">{{user.first_name}}</h3>
            </div>
    </div>
    <div class="row text-center">
            <div style="color:white;background-color: #547dc4;border-radius: 5px;" class="col-sm-4 col-md-2 col-md-offset-3 col-lg-2 col-lg-offset-3">
                    <h3>Last Name</h3>
            </div>
            <div style="color:white;background-color: #547dc4;border-radius: 5px;" class="col-sm-8 col-md-4 col-lg-4">
                    <h3 class="pull-left">{{user.last_name}}</h3>
            </div>
    </div>
    <div class="row text-center">
            <div style="color:white;background-color: #547dc4;border-radius: 5px;" class="col-sm-4 col-md-2 col-md-offset-3 col-lg-2 col-lg-offset-3">
                    <h3>Email</h3>
            </div>
            <div style="color:white;background-color: #547dc4;border-radius: 5px;" class="col-sm-8 col-md-4 col-lg-4">
                    <h3 class="pull-left">{{user.email}}</h3>
            </div>
    </div>
    <div class="row text-center">
            <div style="color:white;background-color: #547dc4;border-radius: 5px;" class="col-sm-4 col-md-2 col-md-offset-3 col-lg-2 col-lg-offset-3">
                    <h3>Username</h3>
            </div>
            <div style="color:white;background-color: #547dc4;border-radius: 5px;" class="col-sm-8 col-md-4 col-lg-4">
                    <h3 class="pull-left">{{user.username}}</h3>
            </div>
    </div>
{% endblock %}